const dataBase = [
  {
    id: 1,
    name: "Ernestina",
    country: "England",
    email: "Ernestina_Klein@yahoo.com",
    numberOfEmployees: 30,
    industry: "veterinary",
  },
  {
    id: 2,
    name: "Jalon",
    country: "England",
    email: "Jalon61@hotmail.com",
    numberOfEmployees: 100,
    industry: "woodcut",
  },
  {
    id: 3,
    name: "Aniya",
    country: "Spain",
    email: "Aniya_Greenholt54@gmail.com",
    numberOfEmployees: 2000,
    industry: "woodcut",
  },
  {
    id: 4,
    name: "Karelle",
    country: "Spain",
    email: "Karelle9@yahoo.com",
    numberOfEmployees: 100,
    industry: "veterinary",
  },
  {
    id: 5,
    name: "Daryl",
    country: "Poland",
    email: "Daryl_Hilpert6@gmail.com",
    numberOfEmployees: 150,
    industry: "automotive",
  },
  {
    id: 6,
    name: "Lewis",
    country: "Spain",
    email: "Lewis28@gmail.com",
    numberOfEmployees: 100,
    industry: "veterinary",
  },
  {
    id: 7,
    name: "Myrtie",
    country: "Poland",
    email: "Myrtie71@hotmail.com",
    numberOfEmployees: 10,
    industry: "automotive",
  },
  {
    id: 8,
    name: "Travis",
    country: "Spain",
    email: "Travis_Johnston4@gmail.com",
    numberOfEmployees: 3,
    industry: "veterinary",
  },
  {
    id: 9,
    name: "Santino",
    country: "Poland",
    email: "Santino94@hotmail.com",
    numberOfEmployees: 111,
    industry: "veterinary",
  },
  {
    id: 10,
    name: "Clement",
    country: "England",
    email: "Clement.Rogahn81@hotmail.com",
    numberOfEmployees: 523,
    industry: "veterinary",
  },
];

export { dataBase };
