const dataBase = [
  {
    id: 1,
    name: "Ernestina",
    country: "England",
    email: "Ernestina_Klein@yahoo.com",
    numberOfEmployees: 30,
    industry: "veterinary",
  },
  {
    id: 2,
    name: "Jalon",
    country: "England",
    email: "Jalon61@hotmail.com",
    numberOfEmployees: 100,
    industry: "woodcut",
  },
  {
    id: 3,
    name: "n/a",
    country: "Spain",
    email: "Aniya_Greenholt54@gmail.com",
    numberOfEmployees: 2000,
    industry: "woodcut",
  },
  {
    id: 4,
    name: "Karelle",
    country: "Spain",
    email: "Karelle9@yahoo.com",
    numberOfEmployees: 100,
    industry: "veterinary",
  },
  {
    id: 5,
    name: "Daryl",
    country: "Poland",
    email: "Daryl_Hilpert6@gmail.com",
    numberOfEmployees: 150,
    industry: "automotive",
  },
  {
    id: 6,
    name: "Lewis",
    country: "Spain",
    email: "Lewis28@gmail.com",
    numberOfEmployees: 100,
    industry: "veterinary",
  },
  {
    id: 7,
    name: "Myrtie",
    country: "Poland",
    email: "Myrtie71@hotmail.com",
    numberOfEmployees: 10,
    industry: "automotive",
  },
  {
    id: 8,
    name: "Travis",
    country: "Spain",
    email: "Travis_Johnston4@gmail.com",
    numberOfEmployees: 3,
    industry: "veterinary",
  },
  {
    id: 9,
    name: "Santino",
    country: "Poland",
    email: "Santino94@hotmail.com",
    numberOfEmployees: 111,
    industry: "veterinary",
  },
  {
    id: 10,
    name: "Clement",
    country: "England",
    email: "Clement.Rogahn81@hotmail.com",
    numberOfEmployees: 523,
    industry: "veterinary",
  },
];

const database2 = [
  {
    id: 1,
    name: "Centidel",
    country: "United States",
    industry: "Telecommunications Equipment",
    numberOfEmployees: 60,
  },
  {
    id: 2,
    name: "Dynazzy",
    country: "Indonesia",
    industry: "Department/Specialty Retail Stores",
    numberOfEmployees: 70,
  },
  {
    id: 3,
    name: "Myworks",
    country: "United States",
    industry: "Other Specialty Stores",
    numberOfEmployees: 24,
  },
  {
    id: 4,
    name: "Mycat",
    country: "Cuba",
    industry: "Air Freight/Delivery Services",
    numberOfEmployees: 88,
  },
  {
    id: 5,
    name: "Teklist",
    country: "Indonesia",
    industry: "Plastic Products",
    numberOfEmployees: 30,
  },
  {
    id: 6,
    name: "Meembee",
    country: "China",
    industry: "n/a",
    numberOfEmployees: 42,
  },
  {
    id: 7,
    name: "Roomm",
    country: "Canada",
    industry: "Other Specialty Stores",
    numberOfEmployees: 51,
  },
  {
    id: 8,
    name: "Dazzlesphere",
    country: "Malaysia",
    industry: "Major Banks",
    numberOfEmployees: 19,
  },
  {
    id: 9,
    name: "Twitterbeat",
    country: "Armenia",
    industry: "Semiconductors",
    numberOfEmployees: 30,
  },
  {
    id: 10,
    name: "Feedfire",
    country: "Poland",
    industry: "Newspapers/Magazines",
    numberOfEmployees: 69,
  },
  {
    id: 11,
    name: "Shuffledrive",
    country: "China",
    industry: "Hotels/Resorts",
    numberOfEmployees: 37,
  },
  {
    id: 12,
    name: "Omba",
    country: "United States",
    industry: "Major Chemicals",
    numberOfEmployees: 81,
  },
  {
    id: 13,
    name: "Twitterbeat",
    country: "Vietnam",
    industry: "Building Products",
    numberOfEmployees: 95,
  },
  {
    id: 14,
    name: "Tagchat",
    country: "China",
    industry: "Electric Utilities: Central",
    numberOfEmployees: 69,
  },
  {
    id: 15,
    name: "Jaxbean",
    country: "Sweden",
    industry: "Real Estate Investment Trusts",
    numberOfEmployees: 53,
  },
  {
    id: 16,
    name: "Gabvine",
    country: "Kenya",
    industry: "n/a",
    numberOfEmployees: 68,
  },
  {
    id: 17,
    name: "Blogtags",
    country: "Indonesia",
    industry: "n/a",
    numberOfEmployees: 56,
  },
  {
    id: 18,
    name: "Skiptube",
    country: "China",
    industry: "Metal Fabrications",
    numberOfEmployees: 47,
  },
  {
    id: 19,
    name: "Brightdog",
    country: "Indonesia",
    industry: "n/a",
    numberOfEmployees: 82,
  },
  {
    id: 20,
    name: "Shuffledrive",
    country: "China",
    industry: "Major Banks",
    numberOfEmployees: 33,
  },
];

export { dataBase, database2 };
